# Site settings
title: Rose Lang
email: ian.riley.915@gmail.com
description: >
  Jekyll Template for Project Websites
  providing documentation and blog post pages.
lang: en-US

baseurl: "/lang" # the subpath of your site, e.g. /blog/
url: https://ttowncompiled.github.io/Rose # the base hostname & protocol for your site
git_address: https://github.com/ttowncompiled/Rose
git_edit_address: https://github.com/ttowncompiled/Rose/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: US/Chicago
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
